
export const defaultIcons = [
    {
      name: "FOOD",
      icons: [
        "md/MdSoupKitchen",
        "gi/GiKitchenKnives",
        "gi/GiFrenchFries",
        "gi/GiStairsCake",
        "gi/GiBeerBottle",
        "gi/GiBlender",
        "gi/GiBoba",
        "gi/GiCannedFish",
        "gi/GiCampCookingPot",
        "gi/GiCoffeeCup",
        "gi/GiHamburger",
        "gi/GiPieSlice",
      ],
    },
    {
      name: "FAMILY",
      icons: [
        "md/MdFamilyRestroom",
        // "fa/FaPerson",
        "md/MdChildFriendly",
        "gi/GiBodyHeight",
        "gi/GiCarousel",
        "gi/GiDarkSquad",
        "gi/GiPartyPopper",
        "gi/GiPinata",
        "fa/FaBabyCarriage",
      ],
    },
    {
      name: "BUILDINGS",
      icons: [
        "gi/GiFamilyHouse",
        "fa/FaBuilding",
        "fa/FaStore",
        "gi/GiBarracksTent",
        "fa/FaSchool",
      ],
    },
    {
      name: "EASHTETIC",
      icons: [
        "gi/GiHairStrands",
        "fa/FaAirFreshener",
        "gi/GiLipstick",
        "gi/GiLips",
        "gi/GiProtectionGlasses",
      ],
    },
    {
      name: "CLOTHES",
      icons: [
        "gi/GiFurBoot",
        "fa/FaHatCowboy",
        "gi/GiTravelDress",
        "gi/GiClothes",
        "gi/GiUnderwear",
      ],
    },
    {
      name: "ANIMALS",
      icons: [ "fa/FaDog", "fa/FaCat", "fa/FaFish"],
    },
    {
      name: "HOME",
      icons: [
        "gi/GiHammerNails",
        "gi/GiPillow",
        "gi/GiSpade",
        "gi/GiWashingMachine",
        "fa/FaBath",
        "md/MdElectricBolt",
      ],
    },
    {
      name: "TRANSPORT",
      icons: [
        "md/MdAirportShuttle",
        "md/MdOutlineAirplanemodeActive",
        "md/MdOutlineDirectionsTransit",
        "gi/GiCarWheel",
        "gi/GiJerrycan",
        "gi/GiKickScooter",
        "fa/FaCarCrash",
        "fa/FaMotorcycle",
        "gi/GiFullMotorcycleHelmet",
      ],
    },
    {
      name: "FURNITURE",
      icons: ["gi/GiSofa", "md/MdTableRestaurant", "md/MdChair", "md/MdBed"],
    },
    {
      name: "FUN",
      icons: [
        "gi/GiTheater",
        "gi/GiChessKnight",
        "gi/GiClubs",
        "gi/GiConsoleController",
        "gi/GiKite",
        "gi/GiMaracas",
        "gi/GiPinata",
        "gi/GiTheaterCurtains",
      ],
    },
    {
      name: "LOVE",
      icons: [
        "gi/GiLovers",
        "gi/GiBowTieRibbon",
        "gi/GiBrokenHeart",
        "gi/GiCherish",
        "gi/GiDiamondRing",
        "gi/GiHeartNecklace",
        "gi/GiPresent",
      ],
    },
    {
      name: "GAMES",
      icons: [
        "md/MdOutlineSportsEsports",
        "gi/GiBowlingStrike",
        "gi/GiWarAxe",
        "gi/GiVrHeadset",
      ],
    },
    {
      name: "ACCOUNTS",
      icons: [
        "fa/FaGoogle",
        "fa/FaAmazon",
        "fa/FaApple",
        "fa/FaCcApplePay",
        "fa/FaLinkedin",
        "fa/FaYoutube",
        "fa/FaAirbnb",
        "fa/FaXbox",
        "fa/FaSteam",
        "fa/FaGithub",
      ],
    },
    {
      name: "SPORTS",
      icons: [
        "gi/GiAmericanFootballHelmet",
        "gi/GiAmericanFootballBall",
        "fa/FaBowlingBall",
        "gi/GiEightBall",
        "gi/GiSoccerBall",
        "gi/GiBoxingGlove",
        "gi/GiBiceps",
        "gi/GiCycling",
        "gi/GiMuscleUp",
        "gi/GiWeightLiftingUp",
      ],
    },
    {
      name: "HEALTH",
      icons: [
        "md/MdHealthAndSafety",
        "gi/GiHealthNormal",
        "gi/GiMedicinePills",
        "fa/FaBriefcaseMedical",
        "fa/FaHandHoldingMedical",
        "gi/GiParmecia",
        "gi/GiPill",
        "gi/GiWeightScale",
      ],
    },
    {
      name: "ELECTRONICS",
      icons: [
        "md/MdOutlinePhoneIphone",
        "md/MdLaptopWindows",
        "gi/GiKeyboard",
        "gi/GiPc",
        "fa/FaCamera",
        "md/MdWatch",
      ],
    },
    {
      name: "TRAVEL",
      icons: [
        "md/MdOutlineTravelExplore",
        "gi/GiCamel",
        "gi/GiCanoe",
        "gi/GiColiseum",
        "gi/GiPalmTree",
        "gi/GiWinterHat",
      ],
    },
    { name: "EDUCATION", icons: ["gi/GiGraduateCap", "gi/GiOpenBook"] },
    {
      name: "VICES",
      icons: [
        "gi/GiHemp",
        "gi/GiPoliceCar",
        "gi/GiCigarette",
        "fa/FaBeer",
        "gi/GiBeerBottle",
      ],
    },
    {
      name: "ART",
      icons: [
        "gi/GiPalette",
        "gi/GiPaintBrush",
        "gi/GiPencilBrush",
        "gi/GiSaxophone",
        "gi/GiMusicalScore",
      ],
    },
    {
      name: "OTHERS",
      icons: [
        "gi/GiAlienStare",
        "md/MdLocalGroceryStore",
        "md/MdOutlineGTranslate",
        "gi/GiPistolGun",
        "gi/GiBrickPile",
        "gi/GiBrickWall",
        "gi/GiBroom",
        "gi/GiBrute",
        "gi/GiBullseye",
        "gi/GiDoubleQuaver",
        "gi/GiHandcuffed",
        "gi/GiMicroscope",
        "gi/GiRecycle",
        "gi/GiTrashCan",
        "gi/GiTurd",
        "gi/GiWallet",
        "gi/GiPiggyBank",
        "fa/FaSimCard",
      ],
    },
  ];